In [36]:
import numpy as np

In [35]:
def matriz_dirac(mu):
    if mu == 0:
        return np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, -1]])
    elif mu == 1:
        return np.array([[0, 0, 0, 1], [0, 0, 1, 0], [0, -1, 0, 0], [-1, 0, 0, 0]])
    elif mu == 2:
        return np.array([[0, 0, 0, -1j], [0, 0, 1j, 0], [0, 1j, 0, 0], [-1j, 0, 0, 0]])
    elif mu == 3:
        return np.array([[0, 0, 1, 0], [0, 0, 0,-1], [-1 ,0 ,0 ,0], [0 ,1 ,0 ,0]])

In [37]:
eta = np.diag([1,-1,-1,-1])
I = np.eye(4)

In [38]:
i = [0,1,2,3]
for mu in i:
    for nu in i:
        gamma_mu = matriz_dirac(mu)
        gamma_nu = matriz_dirac(nu)

        result = gamma_mu @ gamma_nu + gamma_nu @ gamma_mu 
        lado_izq =  result
        lado_derecho =  2 * eta[mu][nu] * np.eye(4)

        print(f"mu = {mu}, nu = {nu}")
        print("Lado izquierdo:\n", lado_izq)
        print("Lado derecho:\n", lado_derecho)

        if np.array_equal(lado_izq,lado_derecho):
            print("La igualdad se cumple.\n")
        else:
            print("La igualdad no se cumple.\n")
            
eta[0][2]

mu = 0, nu = 0
Lado izquierdo:
 [[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]
Lado derecho:
 [[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]
La igualdad se cumple.

mu = 0, nu = 1
Lado izquierdo:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Lado derecho:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La igualdad se cumple.

mu = 0, nu = 2
Lado izquierdo:
 [[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]
Lado derecho:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La igualdad se cumple.

mu = 0, nu = 3
Lado izquierdo:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Lado derecho:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La igualdad se cumple.

mu = 1, nu = 0
Lado izquierdo:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Lado derecho:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La igualdad se cumple.

mu = 1, nu = 1
Lado izquierdo:
 [[-

0