In [11]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

# Punto 6

In [3]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])

In [12]:
def GausSeidel(A,b,x0,w, itmax=1000, tolerancia= 1e-9):
    
    x = x0.copy()
    
    for it in range(1,itmax):
        
        #xn = np.zeros_like(x0)
        
        for i in range(A.shape[0]):
            
            sum_ = 0.
            
            for j in range(A.shape[1]):
                
                if j!=i:
                    sum_ += A[i,j]*x[j]
                    
            x[i] = (1-w)*x[i-1]+w*(b[i] - sum_)/A[i,i]
            
        #print(it,x)
        
        residuo = np.linalg.norm( np.dot(A,x) - b )
        #x = xn.copy()
        #print(residuo)
        
        if np.allclose(residuo,tolerancia,atol=tolerancia):
            break
        
    return x,it

In [13]:
x0 = np.array([0.,0.,0.])
it=20

print(GausSeidel(A,b,x0,1))
for N in range(1,it):
    w=2/(1+np.pi/N)
    #print(w)
    #print(GausSeidel(A,b,x0,w))
    
    


(array([1., 1., 1.]), 16)


# Punto 9

In [163]:
def mayor_valor(matriz):
    valor=-np.inf
    for i in range(len(matriz)):
        for j in range(len(matriz[i])):
            if i!=j and valor<=matriz[i,j]:
                
                valor=matriz[i,j]
                coords=np.array([i,j])
    return valor, coords
    

In [204]:
def Vectores_Propios(A, itmax=1000):
    RV =np.identity(len(A))
    for it in range(itmax):
        R = np.eye(A.shape[0])
        
        mv = mayor_valor(A)
        v = mv[0]
        coords = mv[1]
        if A[coords[0], coords[0]] == A[coords[1], coords[1]]:
            theta = np.pi / 4
        else:
            t = 2 * v / (A[coords[1], coords[1]] - A[coords[0], coords[0]])
            theta = 0.5 * np.arctan(t)
        
        R[coords[1], coords[0]] = -np.sin(theta)      
        R[coords[0], coords[1]] = np.sin(theta)
        R[coords[0], coords[0]] = np.cos(theta)
        R[coords[1], coords[1]] = np.cos(theta)
        
        R_inv = np.linalg.inv(R)
        RV = np.dot(R.T, RV)
        A = R_inv @ A @ R
        
    VP = np.diag(A)
    V = np.linalg.inv(RV)
    return VP, V
                
                
                

In [205]:
a=np.array([[4,1,1],[1,3,2],[1,2,5]])


In [206]:
Valores,Vectores=Vectores_Propios(a)


In [207]:
Valores

array([3.39729482, 1.70759867, 6.89510652])

In [208]:
Vectores

array([[ 0.8856695 , -0.17094212,  0.43170398],
       [-0.07555865,  0.86430837,  0.49725438],
       [-0.45812708, -0.47302201,  0.75257541]])

In [209]:
np.linalg.eig(a)

(array([6.89510652, 3.39729507, 1.70759841]),
 array([[ 0.43170413,  0.88573564,  0.17059871],
        [ 0.49725362, -0.07589338, -0.86427949],
        [ 0.75257583, -0.45794385,  0.47319874]]))