In [3]:
import sympy as sym
import numpy as np

# Punto 13

In [4]:
Jx=np.ones([3,3])
Jy=np.ones([3,3])
Jz=np.ones([3,3])

LC=np.array([Jx,Jy,Jz])
MJ=np.zeros([3,3,3])

for i in range(len(Jx)):
    for j in range(len(Jy)):
        for k in range(len(Jz)):

            if (i>j and ((i+j)%2==1)) or (j>k and k>i):
                LC[i,j,k]=-1
                #print(k,j,i)
            
            if i==j or j==k or i ==k:
                LC[i,j,k]=0
    MJ[i]=LC[i].T
LC

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  1.],
        [ 0., -1.,  0.]],

       [[ 0.,  0., -1.],
        [ 0.,  0.,  0.],
        [ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.],
        [-1.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [25]:


for i in range(len(Jx)):
    for j in range(len(Jy)):
        for k in range(len(Jz)):
            ecu_L=MJ[i]@MJ[j]-MJ[j]@MJ[i]
            #print(MJ[0]@MJ[0])
            ecu_R=LC[i,j,k]*MJ[k]
            
            #print(ecu_R)
            #print(ecu_L==ecu_R)
            

# Punto 14

In [6]:
sx=np.array([[0,1],[1,0]])
sy=np.array([[0,-1j],[1j,0]])
sz=np.array([[1,0],[0,1]])

Ms=np.array([sx,sy,sz])

In [15]:
LC[0,0,0]

0.0

In [7]:
LCi=np.zeros([3,2,2])
for i in range(LCi.shape[0]):
    for j in range(LCi.shape[1]):
        for k in range(LCi.shape[2]):
            if j>k:
                LCi[i,j,k]=1
            elif k>j:
                LCi[i,j,k]=-1
                
LCi

array([[[ 0., -1.],
        [ 1.,  0.]],

       [[ 0., -1.],
        [ 1.,  0.]],

       [[ 0., -1.],
        [ 1.,  0.]]])

In [29]:
for i in range(len(Ms)):
    for j in range(len(sy)):
        for k in range(len(sz)):
            
            ecu_L=Ms[i]@Ms[j]-Ms[j]@Ms[i]
          
            ecu_R=2j*(LCi[i,j,k]*Ms[k])
            print(ecu_R==ecu_L)

[[ True  True]
 [ True  True]]
[[ True False]
 [False  True]]
[[False False]
 [False False]]
[[False  True]
 [ True False]]
[[False  True]
 [ True False]]
[[False False]
 [False False]]
[[ True False]
 [False  True]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[ True False]
 [False  True]]
[[ True False]
 [False  True]]
[[ True  True]
 [ True  True]]


array([[ True,  True],
       [ True,  True]])