In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym

# Punto 6

In [91]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])

In [329]:
A[1,2]

1.0

In [268]:
for r in range(4,1):
    print(r)
    
print(r)


1


In [443]:
def GausSeidel(A,b,x0,w, itmax=1000, tolerancia= 1e-9):
    
    x = x0.copy()
    
    for it in range(1,itmax):
        
        #xn = np.zeros_like(x0)
        
        for i in range(A.shape[0]):
            
            sum_ = 0.
            
            for j in range(A.shape[1]):
                
                if j!=i:
                    sum_ += A[i,j]*x[j]
                    
            x[i] = (1-w)*x[i-1]+w*(b[i] - sum_)/A[i,i]
            
        #print(it,x)
        
        residuo = np.linalg.norm( np.dot(A,x) - b )
        #x = xn.copy()
        #print(residuo)
        
        if np.allclose(residuo,tolerancia,atol=tolerancia):
            break
        
    return x,it

In [444]:
x0 = np.array([0.,0.,0.])
it=20
for N in range(1,it):
    w=2/(1+np.pi/N)
    print(w)
    print(GausSeidel(A,b,x0,w))

0.48290601401044775
(array([1., 1., 1.]), 11)
0.7779690592966855
(array([1., 1., 1.]), 14)
0.9769452873910434
(array([1., 1., 1.]), 16)
1.1201983070231147
(array([1., 1., 1.]), 17)
1.2282609098099249
(array([1., 1., 1.]), 21)
1.312681548470413
(array([1., 1., 1.]), 28)
1.3804537884929204
(array([1., 1., 1.]), 35)
1.4360603997530677
(array([1., 1., 1.]), 43)
1.4825073212020587
(array([1., 1., 1.]), 53)
1.5218855527786235
(array([1., 1., 1.]), 64)
1.5556946476191547
(array([1., 1., 1.]), 78)
1.585038017404995
(array([1., 1., 1.]), 94)
1.6107456406550908
(array([1., 1., 1.]), 114)
1.6334538199480688
(array([1., 1., 1.]), 139)
1.6536585609016916
(array([1., 1., 1.]), 172)
1.6717522193221865
(array([1., 1., 1.]), 217)
1.6880492314961129
(array([1., 1., 1.]), 282)
1.7028045422059195
(array([1., 1., 1.]), 382)
1.7162270390625716
(array([1., 1., 1.]), 560)


# Punto 9

In [222]:
a=np.array([[4.,1.,1.],[1.,3.,2.],[1.,2.,5.]])


In [223]:
def mayor_valor(matriz):
    valor=0
    for i in range(len(matriz)):
        for j in range(len(matriz[i])):
            if i!=j and valor<=abs(matriz[i,j]):
                
                valor=matriz[i,j]
                coords=np.array([i,j])
    return valor, coords
    

In [406]:
def Valores_Propios (A,itmax=10000):
    RV=np.identity(len(A))
    for it in range(itmax):
        
        R=np.zeros([A.shape[0],A.shape[1]])
        for i in range(A.shape[0]):
            for j in range(A.shape[1]):
                
                mv=mayor_valor(A)
                v=mv[0]
                coords=mv[1]
                
                if A[coords[0],coords[0]]==A[coords[1],coords[1]]:
                    theta=np.pi/4
                else:
                    theta=0.5*np.arctan(2*v/(A[coords[0],coords[0]]-A[coords[1],coords[1]]))
                    
                    
                if coords[0]==i and coords[1]==j:
                    R[i,j]=-np.sin(theta)
                elif coords[1]==i and coords[0]==j:
                    R[i,j]=np.sin(theta)
                elif i==j:
                    R[i,j]=1
                elif coords[0]==i==j or coords[1]==j==i:
                    R[i,j]=np.cos(theta)
        
        R_inv=np.linalg.inv(R)
        RV=RV@R
        #print(RV)
        A=R_inv@A@R
        
        
            
    return A,RV
                
                
                

In [407]:
vp=Valores_Propios(a)[0]
VP=np.array([])
for i in range(len(vp)):
    VP=np.append(VP,vp[i,i])
VP



array([3.39712968, 1.70755584, 6.89531447])

In [408]:
lista=Valores_Propios(a)[1]


[[ 0.96182029 -0.19249341  0.52463695]
 [-0.13648529  0.99087473  0.60703158]
 [-0.61531146 -0.54444386  0.91567933]]


In [409]:
np.linalg.eig(a)

(array([6.89510652, 3.39729507, 1.70759841]),
 array([[ 0.43170413,  0.88573564,  0.17059871],
        [ 0.49725362, -0.07589338, -0.86427949],
        [ 0.75257583, -0.45794385,  0.47319874]]))

0.0