In [3]:
import sympy as sym
import numpy as np

In [38]:
Jx=np.ones([3,3])
Jy=np.ones([3,3])
Jz=np.ones([3,3])

MJ=np.array([Jx,Jy,Jz])


for k in range(len(Jx)):
    for j in range(len(Jy)):
        for i in range(len(Jz)):

            if i-j==1 or i-j==-2:
                MJ[k,j,i]=-1
                
            if i==j or j==k or i ==k:
                MJ[k,j,i]=0
MJ

array([[[ 0.,  0.,  0.],
        [ 0.,  0., -1.],
        [ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.],
        [ 0.,  0.,  0.],
        [-1.,  0.,  0.]],

       [[ 0., -1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [53]:
MJ[0]@MJ[1]-MJ[1]@MJ[0]

for k in range(len(Jx)):
    for j in range(len(Jy)):
        for i in range(len(Jz)):
            ecu_L=MJ[i]@MJ[j]-MJ[j]@MJ[i]
            ecu_R=MJ[k,j,i]*MJ[k]
            
            #print('Izquierda',ecu_L,'Derecha', ecu_R)
            

Izquierda [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] Derecha [[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
Izquierda [[ 0.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  0.]] Derecha [[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
Izquierda [[ 0.  0.  1.]
 [ 0.  0.  0.]
 [-1.  0.  0.]] Derecha [[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
Izquierda [[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]] Derecha [[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
Izquierda [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] Derecha [[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
Izquierda [[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]] Derecha [[-0. -0. -0.]
 [-0. -0.  1.]
 [-0. -1. -0.]]
Izquierda [[ 0.  0. -1.]
 [ 0.  0.  0.]
 [ 1.  0.  0.]] Derecha [[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
Izquierda [[ 0.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]] Derecha [[ 0.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
Izquierda [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] Derecha [[ 0.  0.  0.]
 [ 0.  0. -0.]
 [ 0.  0.  0.]]
Izquierda [[0. 0. 0.]
 [0. 0. 0.]
 [0