In [367]:
import numpy as np
import math
from math import e
import sympy as sym
import matplotlib.pyplot as plt
from matplotlib import rc

In [397]:
import numpy as np
import sympy as sym


#Punto 1.9.5 Calcular todas las raıces reales de los primeros 20 polinomios de.
#LAGUERRE
def Laguerre(n):
    x= sym.Symbol("x",Real=True)
    y= sym.Symbol("y",Real=True)
    e=np.e
    y= (e**(-x))*(x**n)
    
    p= ((e**x)/np.math.factorial(n))*sym.diff(y,x,n)
    poly=sym.lambdify([x],p,'numpy')
    return poly

def Derivative(f,x,h=1e-6):
    
    return (f(x+h)-f(x-h))/(2*h)




In [405]:
def GetNewtonMethod(f,df,xn,itmax=1000,precision=1e-9):
    
    error = 1
    it=0
    
    while error > precision and it < itmax:
        
        try:
            
            xn1 = xn - f(xn)/df(f,xn)
            error = np.abs(f(xn)/df(f,xn))
            
        except ZeroDivisionError:
            print('Division por cero')
            
        xn = xn1
        it += 1
    
    if it == itmax:
        return False
    else:
        return xn

In [406]:
def GetAllRoots(f,x, tolerancia=5):
    Roots = np.array([])
    for i in x:
        root = GetNewtonMethod(f,Derivative,i)
        
        if root != False:
            
            croot = np.round( root, tolerancia )
            
            if croot not in Roots:
                Roots = np.append(Roots,croot)
                
    Roots.sort()
    
    return Roots

In [428]:
Raices=np.array([])
n=20
x=np.linspace(1,60,2000)
for i in range(1,n+1): 
    #f=laguerre(i)

    
    raices = GetAllRoots(Laguerre(i),x)
    if i>1:
        print('\nLas raices de los polinomios de Laguerre de grado '+str(i)+' son: ')
        print(raices)
    else:
        print('\nLa raíz del polinomio de Laguerre de grado '+str(i)+' es: ')
        print(raices)
    Raices=np.append(Raices,raices)
    
    


La raíz del polinomio de Laguerre de grado 1 es: 
[1.]

Las raices de los polinomios de Laguerre de grado 2 son: 
[0.58579 3.41421]

Las raices de los polinomios de Laguerre de grado 3 son: 
[0.41577 2.29428 6.28995]

Las raices de los polinomios de Laguerre de grado 4 son: 
[0.32255 1.74576 4.53662 9.39507]

Las raices de los polinomios de Laguerre de grado 5 son: 
[ 0.26356  1.4134   3.59643  7.08581 12.6408 ]

Las raices de los polinomios de Laguerre de grado 6 son: 
[ 0.22285  1.18893  2.99274  5.77514  9.83747 15.98287]

Las raices de los polinomios de Laguerre de grado 7 son: 
[ 0.19304  1.02666  2.56788  4.90035  8.18215 12.73418 19.39573]

Las raices de los polinomios de Laguerre de grado 8 son: 
[ 0.17028  0.9037   2.25109  4.2667   7.04591 10.75852 15.74068 22.86313]

Las raices de los polinomios de Laguerre de grado 9 son: 
[ 0.15232  0.80722  2.00514  3.78347  6.20496  9.37299 13.46624 18.8336
 26.37407]

Las raices de los polinomios de Laguerre de grado 10 son: 
[ 0.13779

In [429]:
Raices

array([ 1.     ,  0.58579,  3.41421,  0.41577,  2.29428,  6.28995,
        0.32255,  1.74576,  4.53662,  9.39507,  0.26356,  1.4134 ,
        3.59643,  7.08581, 12.6408 ,  0.22285,  1.18893,  2.99274,
        5.77514,  9.83747, 15.98287,  0.19304,  1.02666,  2.56788,
        4.90035,  8.18215, 12.73418, 19.39573,  0.17028,  0.9037 ,
        2.25109,  4.2667 ,  7.04591, 10.75852, 15.74068, 22.86313,
        0.15232,  0.80722,  2.00514,  3.78347,  6.20496,  9.37299,
       13.46624, 18.8336 , 26.37407,  0.13779,  0.72945,  1.80834,
        3.40143,  5.5525 ,  8.33015, 11.84379, 16.27926, 21.99659,
       29.9207 ,  0.1258 ,  0.66542,  1.64715,  3.09114,  5.02928,
        7.50989, 10.60595, 14.43161, 19.17886, 25.21771, 33.49719,
        0.11572,  0.61176,  1.51261,  2.83375,  4.59923,  6.84453,
        9.62132, 13.00605, 17.11686, 22.15109, 28.48797, 37.09912,
        0.10714,  0.56613,  1.39856,  2.6166 ,  4.23885,  6.29226,
        8.815  , 11.8614 , 15.51076, 19.88464, 25.18526, 31.80

In [430]:
suma=0
val=0
for i in range(1,21): 
    
    Ex=np.polynomial.laguerre.laggauss(i)
    suma+=len(Ex[0])
suma==len(Raices)

True